# Generated by Django 3.2 on 2023-11-30 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20231128_1013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student_details',
            old_name='name',
            new_name='course',
        ),
        migrations.AddField(
            model_name='student_details',
            name='email',
            field=models.CharField(default='no', max_length=250),
        ),
        migrations.AddField(
            model_name='student_details',
            name='fullname',
            field=models.CharField(default='no', max_length=250),
        ),
    ]
