# Generated by Django 3.2 on 2023-12-01 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_auto_20231130_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.CharField(default='no', max_length=250),
        ),
        migrations.AddField(
            model_name='course',
            name='fee',
            field=models.IntegerField(default='no'),
        ),
    ]
