# Generated by Django 3.2 on 2023-12-16 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_auto_20231201_1042'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='name',
            new_name='course',
        ),
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.CharField(default='no', max_length=250),
        ),
        migrations.AddField(
            model_name='course',
            name='seats',
            field=models.IntegerField(default='no'),
        ),
        migrations.AddField(
            model_name='course',
            name='slot',
            field=models.CharField(default='no', max_length=250),
        ),
        migrations.AddField(
            model_name='student_details',
            name='seats',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student_details',
            name='slot',
            field=models.CharField(default='0', max_length=250),
        ),
    ]
