# Generated by Django 3.2 on 2023-12-16 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_auto_20231216_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='seats',
            field=models.IntegerField(default=0),
        ),
    ]
