# Generated by Django 3.2 on 2023-12-16 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_alter_course_seats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='seats',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='student_details',
            name='mobile_no',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='student_details',
            name='seats',
            field=models.IntegerField(default='0'),
        ),
    ]
